- Task-1/akshayw1.txt
> Task done by Akshay Waghmare IEC2022117

- Task-1/IIT2022127.txt
> Task-1 done.

- Task-1/Harshal5167.txt
> Task-1 completed

- Task-1/saiushasree1.txt
> Task-1_DESIGN

- Task-1/anushkp1107.txt
- anushkp1107.txt
Issue: 1
Task-1 submitted by anushkp1107
> Task-1 Design

- Task-1/muffinboy19
Issue: 1
this is the updated file and it contains the link to the Figma ..
> this is the desgin task-1

- Task-1/esmika-001.txt
> Task done by esmika-001

- Task-1/shashank-lol.txt
> User Flow Task-1

- Task-1/Pragatii20.txt
> Task-1 done by Pragatii20

- Task-1/Tiyasa9.txt
> Task-1 done Tiyasa9

- Task-1/oshankiii12.txt
> Task1 done by oshankiii12

- Task-1/lavishmeena2764.txt
> Task-1 done by Lavishmeena2764

- Task-1/k7aditya.txt
> Design Task 1 done

- Task-1/atharva0192.txt
Issue: 1
Short description of what this resolves:
UserFlow for the discovery app by atharva0192
Changes proposed in this pull request and/or Screenshots of changes:
Successfully added atharva0192.txt with figma link to TASK 1 folder.
> Task 1 Done

- Task-1/JackofAllCodez.txt
> Task-1 Done

- Task-1/tonyStark-Jr.txt
> Created new file tonyStark-Jr.txt with figma link in it

- Task-1/Tej-as1.txt
> Link Added

- Task-1/Hannah2k23.txt
> Task 1 completed

- Task-1/disha.txt
> Task1 done by DISHASONI99

- Design Contest Task - 2/bhupesh98-Design-Task2.ai
Issue: 96
##Changes:
Added bhupesh98-Design-Task2.ai under Design Contest Task - 2
> Task-2 Completed

- Design Contest Task - 2/DebjyotiRay.txt
- Design Contest Task-1/DebjyotiRay.txt
> Task2 by DebjyotiRay

- Design Contest Task - 2/JackofAllCodez.txt
- Design Contest Task-1/JackofAllCodez.txt
> Task-1 and 2 Done

- Design Contest Task - 2/task2.txt
> task2 done

- Tej-as1.txt
> Task2 Completed

- Design Contest Task - 2/atharva0192.txt
> CONTEST TASK 2 DONE

- Design Contest Task-1/Harshal5167.txt
> completed Task1

- Design Contest Task - 2/saiushasree1.txt
> Task_2_Done

- Design Contest Task - 2/lavishmeena2764.txt
> task-2 done by lavishmeena2764

- Design Contest Task - 2/oshankiii12.txt
- Design Contest Task-1/oshankiii12.txt
> Task 2 done by oshankiii12

- Design Contest Task-1/oshankiii12.txt
> Task -1 done by oshankiii12

- Design Contest Task - 2/Tiyasa9.txt
> task - 2 done by Tiyasa9

- Design Contest Task - 2/Tiyasa9.txt
- Design Contest Task-1/Tiyasa9.txt
> Task 1 done by Tiyasa9

- Design Contest Task - 2/Nandinig24_task2.txt
> task done by Nandinig24

- Design Contest Task - 2/deepanshu task2.txt
> task 2 done
